# Generated by Django 3.2.7 on 2021-09-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(null=0)),
                ('dislikes', models.IntegerField(null=0)),
            ],
        ),
    ]
